Update third.yml

diff --git a/.github/workflows/third.yml b/.github/workflows/third.yml
--- a/.github/workflows/third.yml
+++ b/.github/workflows/third.yml
@@ -214,6 +214,13 @@ jobs:
       GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
 
     steps:
+      - name: Verifying Branch of Deployment
+        run: |
+          if [ "$GITHUB_REF_NAME" == "main" ] || [ "$GITHUB_REF_NAME" == "stg-1" ] || [ "$GITHUB_REF_NAME" == "stg" ]; then
+            echo "You can't trigger the Manual workflow form $GITHUB_REF_NAME Branch, Please carefully Selsct Your Brnach"
+            exit 1
+          fi
+          
       - name: 'Checkout code'
         uses: actions/checkout@v2
         
